Algoritmo "FazSomaProcedimento2"
Var
   X, Y: Inteiro
Procedimento Soma (A, B: Inteiro)
inicio
      Limpatela
      EscrevaL("Recebi o valor ", A)
      EscrevaL("Recebi o valor ", B)
      EscrevaL("A soma entre os dois e ", A + B)
FimProcedimento
Inicio
      X <- 0
      y <- 0
      Escreva("Insira um numero: ")
      Leia (X)
      Escreva("Insira outro numero: ")
      Leia (Y)
      Soma(X,Y)
Fimalgoritmo